sudo: required
services:
  - docker

before_install: 

  - docker build -t botlasai/docker-react -f Dockerfile.dev .

script: 
  - docker run  botlasai/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-west-1-874080003945
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  
